### ISSUE TITLE
Unable to create neutron ports 

### ISSUE THREAD

**Issue by prashantabkari** [cloudify-examples/cloudify-environment-setup#15]
Hi - Using this procedure i am trying to bootstrap the manager on OpenStack using its blueprint but getting the following error. I have set the relevant OPENSTACK paths, using Keystone v3 and doing it in its own virtual environment.. 

Stuck with this issue and not able to proceed with the installation. 

2017-12-22 03:33:10.366  CFY <cloudify-environment-setup-latest> [cloudify_security_group_ysmcl5.create] Task failed 'neutron_plugin.security_group.create' -> No JSON object could be decoded [retry 1/1]
Traceback (most recent call last):
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/cloudify/workflows/tasks.py", line 509, in local_task_wrapper
    result = self.local_task(**self.kwargs)
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/cloudify/dispatch.py", line 616, in dispatch
    return handler.handle_or_dispatch_to_subprocess_if_remote()
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/cloudify/dispatch.py", line 101, in handle_or_dispatch_to_subprocess_if_remote
    return self.handle()
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/cloudify/dispatch.py", line 391, in handle
    result = self.func(*self.args, **kwargs)
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/openstack_plugin_common/__init__.py", line 675, in wrapper
    _put_client_in_kw('neutron_client', NeutronClientWithSugar, kw)
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/openstack_plugin_common/__init__.py", line 787, in _put_client_in_kw
    kw[client_name] = client_class(config=config)
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/openstack_plugin_common/__init__.py", line 867, in __init__
    'neutron_client', neutron_client.Client, *args, **kw)
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/openstack_plugin_common/__init__.py", line 504, in __init__
    cfg = Config.get()
  File "/home/abkari/.virtualenvs/openstackbootstrap/local/lib/python2.7/site-packages/openstack_plugin_common/__init__.py", line 473, in get
    cls.update_config(static_config, json.loads(f.read()))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by EarthmanT** [comment]
Hi this has only been tested against keystone v2.0. Can you try?

**Comment by prashantabkari** [comment]
Hi - Nope. Not tested on v2. I would like to know if v3 support is in
roadmap ?

**Comment by prashantabkari** [comment]
Also does it mean that Cloudify doesn't support v3 ?

**Comment by EarthmanT** [comment]
Please use the example inputs as a guide: https://github.com/cloudify-examples/cloudify-environment-setup/blob/latest/inputs/openstack.yaml.

Cloudify supports the openstack python client libraries (see [versions](http://docs.getcloudify.org/4.2.0/plugins/openstack/#compatibility)), and the authentication methods supported by those libraries.

**Comment by prashantabkari** [comment]
Sorry its still failing. I followed the same steps and it is still failing.. 

this is my openstack input file
username: prashant
password: XXX
tenant_name: prashant
auth_url: https://XXXX:5000/v2.0
region: RegionOne
external_network_name: public
cloudify_image: c76d5b15-bf64-4402-bea6-9f4957ac0c6d # When bootstrap: True
centos_core_image: c76d5b15-bf64-4402-bea6-9f4957ac0c6d
ubuntu_trusty_image: e41430f7-9131-495b-927f-e7dc4b8994c8
small_image_flavor: 2
large_image_flavor: 4
bootstrap: True

this is my openstack rc file that i have sourced
export OS_AUTH_URL=https://XXX:5000/v2.0

export OS_TENANT_ID=366c50e2f90f454d8f9f29f609e2e19a
export OS_TENANT_NAME="prashant"

unset OS_PROJECT_ID
unset OS_PROJECT_NAME
unset OS_USER_DOMAIN_NAME
unset OS_INTERFACE

export OS_USERNAME="prashant"

echo "Please enter your OpenStack Password for project $OS_TENANT_NAME as user $OS_USERNAME: "
read -sr OS_PASSWORD_INPUT
export OS_PASSWORD=$OS_PASSWORD_INPUT

export OS_REGION_NAME="RegionOne"
if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi

export OS_ENDPOINT_TYPE=publicURL
export OS_IDENTITY_API_VERSION=2
